name: regimentcodex
description: Lurking in the darkness are the ghosts of web3, lead by the predetory phantoms they are unstoppable

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  connectivity_plus: ^2.2.0

  dartz: ^0.10.1

  flutter:
    sdk: flutter

  google_fonts: ^2.3.1
  http: ^0.13.4
  provider: ^6.0.2
  rxdart: ^0.27.1
  url_launcher: ^6.0.20
  url_strategy: ^0.2.0
  freezed_annotation: ^2.0.1
  flutter_gen: ^4.1.6
  intl: ^0.17.0

dev_dependencies:

  flutter_lints: ^2.0.0

  build_runner: ^2.0.5

  flutter_test:
    sdk: flutter

  json_serializable: ^6.1.6

  lint: ^1.8.2
  freezed: ^2.0.2
  flutter_gen_runner: ^4.1.6

flutter:

  uses-material-design: true
